# Generated by Django 5.0.6 on 2025-03-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compartido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Conectado'),
        ),
        migrations.AddField(
            model_name='personal',
            name='last_device',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Último dispositivo'),
        ),
        migrations.AddField(
            model_name='personal',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Última IP'),
        ),
        migrations.AddField(
            model_name='personal',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última hora de conexión'),
        ),
        migrations.AddField(
            model_name='personal',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Foto de perfil'),
        ),
    ]
