# Generated by Django 5.0.6 on 2025-01-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compartido", "0004_personal"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_photos/",
                verbose_name="Foto de Perfil",
            ),
        ),
    ]
