# Generated by Django 5.0.6 on 2025-01-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compartido", "0005_personal_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="campos_completados",
            field=models.BooleanField(default=False, verbose_name="Campos completados"),
        ),
    ]
