# Generated by Django 5.0.6 on 2025-01-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compartido", "0008_personal_last_device_personal_last_ip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="is_online",
            field=models.BooleanField(default=False, verbose_name="Conectado"),
        ),
    ]
