# Generated by Django 5.0.6 on 2025-01-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compartido", "0009_personal_is_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="personal",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
